#!/bin/bash

set -e

echo "--- :docker: Building SOCI index"

IMAGE="$BUILDKITE_PLUGIN_SOCI_INDEX_ECR_IMAGE"

if [ -z "$IMAGE" ]; then
  echo "WARNING: plugin `image` parameter not set"
  exit 1
fi

# Download the binary from Buildkite's fork of https://github.com/CloudSnorkel/standalone-soci-indexer
wget https://github.com/buildkite/standalone-soci-indexer/releases/download/v1.0.2-buildkite/standalone-soci-indexer

chmod +x standalone-soci-indexer

./standalone-soci-indexer $IMAGE
